---
  # SERVER SETUP

  - name: Disable firewall
    sudo: yes
    service: name=iptables state=stopped

  - name: Disable selinux
    sudo: yes
    selinux: state=disabled

  - name: Install development tools
    sudo: yes
    action: yum name=$item state=latest
    with_items:
      - '@development'
